{{- if .Values.ingress.enabled }}
--- # --------------------------------------------------------------------------------- Ingress
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "dexidp.fullname" . }}
  labels:
    app.kubernetes.io/component: dexidp
    {{- include "dexidp.labels" . | nindent 4 }}
    {{- include "common.labels" ( dict "labels" (list .Values.global.labels .Values.labels .Values.ingress.labels) ) | nindent 4 }}
  annotations:
    {{- include "common.annotations" ( dict "annotations" (list .Values.global.annotations .Values.annotations .Values.ingress.annotations) ) | nindent 4 }}
spec:
  {{- if .Values.ingress.tls.enabled }}
  tls:
    - hosts:
        - {{ .Values.ingress.host | quote }}
      {{- with .Values.ingress.tls.secretName }}
      secretName: {{ . | quote }}
      {{- end }}
  {{- end }}
  {{- include "common.ingress.className" ( dict "ing" .Values.ingress "global" .Values.global) | nindent 2 }}
  rules:
    - host: {{ .Values.ingress.host }}
      http:
        paths:
        - path: /
          pathType: ImplementationSpecific
          backend:
            service:
              name: {{ include "dexidp.fullname" . }}
              port:
                number: {{ .Values.service.ports.http.port }}
{{- end }}