---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "server.fullname" . }}
  labels:
    app.kubernetes.io/component: server
    {{- include "server.labels" . | nindent 4 }}
    {{- include "common.labels" ( dict "labels" (list .Values.global.labels .Values.labels) ) | nindent 4 }}
  annotations:
    {{- include "common.annotations" ( dict "annotations" (list .Values.global.annotations .Values.annotations) ) | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  revisionHistoryLimit: 3
  minReadySeconds: 10
  selector:
    matchLabels:
      {{- include "server.selectorLabels" . | nindent 6 }}
      argocd.deployment/type: server
  template:
    metadata:
      annotations:
        {{- include "common.annotations" ( dict "annotations" (list .Values.global.annotations .Values.annotations .Values.pod.annotations) ) | nindent 8 }}
        {{/* Adding checksums for all configs, because the apps use all configs... */}}
        checksum/argocd-cm: {{ (lookup "v1" "ConfigMap" .Release.Name "argocd-cm").data | toString | sha256sum | quote }}
        checksum/argocd-cmd-params-cm: {{ (lookup "v1" "ConfigMap" .Release.Name "argocd-cmd-params-cm").data | toString | sha256sum | quote }}
        checksum/argocd-gpg-keys-cm: {{ (lookup "v1" "ConfigMap" .Release.Name "argocd-gpg-keys-cm").data | toString | sha256sum | quote }}
        checksum/argocd-rbac-cm: {{ (lookup "v1" "ConfigMap" .Release.Name "argocd-rbac-cm").data | toString | sha256sum | quote }}
        checksum/argocd-secret: {{ (lookup "v1" "ConfigMap" .Release.Name "argocd-secret").data | toString | sha256sum | quote }}
        checksum/argocd-ssh-known-hosts-cm: {{ (lookup "v1" "ConfigMap" .Release.Name "argocd-ssh-known-hosts-cm").data | toString | sha256sum | quote }}
        checksum/argocd-tls-certs-cm: {{ (lookup "v1" "ConfigMap" .Release.Name "argocd-tls-certs-cm").data | toString | sha256sum | quote }}
      labels:
        {{- include "common.labels" ( dict "labels" (list .Values.global.labels .Values.labels .Values.pod.labels) ) | nindent 8 }}
        {{- include "server.selectorLabels" . | nindent 8 }}
        argocd.deployment/type: server
    spec:
      serviceAccountName: sa-{{ include "server.fullname" . }}
      {{- include "common.images.pullSecrets" ( dict "images" (list .Values.image) "global" .Values.global) | nindent 6 }}
      {{- with .Values.pod.affinity }}
      affinity:
        {{- . | toYaml | nindent 8 }}
      {{- end }}
      {{- with .Values.pod.securityContext }}
      securityContext:
        {{- . | toYaml | nindent 8 }}
      {{- end }}
      {{- with .Values.pod.nodeSelector }}
      nodeSelector:
        {{- . | toYaml | nindent 8 }}
      {{- end }}
      {{- with .Values.pod.tolerations }}
      tolerations:
        {{- . | toYaml | nindent 8 }}
      {{- end }}
      {{- with .Values.pod.schedulerName }}
      schedulerName: {{ . | quote }}
      {{- end }}
      {{- with .Values.pod.priorityClassName }}
      priorityClassName: {{ . | quote }}
      {{- end }}   
      {{- with .Values.pod.terminationGracePeriodSeconds }}
      terminationGracePeriodSeconds: {{ . }}
      {{- end }}
      {{- with .Values.pod.initContainers }}
      initContainers:
        {{- . | toYaml | nindent 8 }}
      {{- end }}
      volumes:
        {{- with (concat .Values.pod.extraVolumes .Values.global.extraVolumes) }}
        {{- . | toYaml | nindent 8 }}
        {{- end }}
        - name: plugins-home
          emptyDir: {}
        - name: tmp
          emptyDir: {}
        - name: ssh-known-hosts
          configMap:
            name:  argocd-ssh-known-hosts-cm
        - name: tls-certs
          configMap:
            name: argocd-tls-certs-cm
        - name: repo-server-tls
          secret:
            secretName: argocd-repo-server-tls
            items:
              - key: tls.crt
                path: tls.crt
              - key: tls.key
                path: tls.key
              - key: ca.crt
                path: ca.crt
            optional: true
        - name: dextls
          secret:
            secretName: argocd-dex-server-tls
            items:
              - key: tls.crt
                path: tls.crt
              - key: ca.crt
                path: ca.crt
            optional: true
        - name:  argocd-cmd-params-cm
          configMap:
            name:  argocd-cmd-params-cm
            items:
              - key: server.profile.enabled
                path: profiler.enabled
            optional: true
      containers:
        {{- with .Values.pod.sidecarContainers }}
        {{- . | toYaml | nindent 8 }}
        {{- end }}
        - name: server
          image: {{ include "common.images.image" ( dict "imageRoot" .Values.image "global" .Values.global "chart" .Chart ) }}
          imagePullPolicy: {{ include "common.images.pullPolicy" ( dict "imageRoot" .Values.image "global" .Values.global ) }}
          {{- with .Values.pod.containers.server.command }}
          command: 
            {{- . | toYaml | nindent 12 }}
          {{- end }}
          {{- with .Values.pod.containers.server.args }}
          args: 
            {{- . | toYaml | nindent 12 }}
          {{- end }}
          {{- with .Values.pod.containers.server.securityContext }}
          securityContext: 
            {{- . | toYaml | nindent 12 }}
          {{- end }}
          {{- with .Values.pod.containers.server.workingDir }}
          workingDir: {{ . | quote }}
          {{- end }}
          {{- with .Values.pod.containers.server.resources }}
          resources:
            {{- . | toYaml | nindent 12 }}
          {{- end }}
          ports:
            - name: http
              containerPort: {{ .Values.service.ports.http.port }}
              protocol: TCP
              {{- with .Values.service.ports.http.hostPort }}
              hostPort: {{ . }}
              {{- end }}
            - name: metrics
              containerPort: {{ .Values.service.ports.metrics.port }}
              protocol: TCP
              {{- with .Values.service.ports.metrics.hostPort }}
              hostPort: {{ . }}
              {{- end }}
          volumeMounts:
            {{- with (concat .Values.pod.containers.server.extraVolumeMounts 
                             .Values.pod.extraVolumeMounts 
                             .Values.global.extraVolumeMounts) }}
            {{- . | toYaml | nindent 12 }}
            {{- end }}
            - name: ssh-known-hosts
              mountPath: /app/config/ssh
            - name: tls-certs
              mountPath: /app/config/tls
            - name: repo-server-tls
              mountPath: /app/config/server/tls 
            - name: dextls
              mountPath: /app/config/dex/tls
            - name: plugins-home
              mountPath: /home/argocd 
            - name: tmp
              mountPath: /tmp 
            - name:  argocd-cmd-params-cm
              mountPath: /home/argocd/params
          envFrom:
            {{- with (concat .Values.pod.containers.server.extraEnvFrom .Values.pod.extraEnvFrom) }}
            {{- . | toYaml | nindent 12 }}
            {{- end }}
            - secretRef:
                name: {{ .Release.Name }}-redis-auth
          env:
            {{- with (concat .Values.pod.containers.server.extraEnvs .Values.pod.extraEnvs) }}
            {{- . | toYaml | nindent 12 }}
            {{- end }}
            {{/*
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: auth
                  name: argocd-redis
            */}}
            - name: ARGOCD_SERVER_INSECURE
              valueFrom:
                configMapKeyRef:
                  key: server.insecure
                  name:  argocd-cmd-params-cm
                  optional: true
            - name: ARGOCD_SERVER_BASEHREF
              valueFrom:
                configMapKeyRef:
                  key: server.basehref
                  name:  argocd-cmd-params-cm
                  optional: true
            - name: ARGOCD_SERVER_ROOTPATH
              valueFrom:
                configMapKeyRef:
                  key: server.rootpath
                  name:  argocd-cmd-params-cm
                  optional: true
            - name: ARGOCD_SERVER_LOGFORMAT
              valueFrom:
                configMapKeyRef:
                  key: server.log.format
                  name:  argocd-cmd-params-cm
                  optional: true
            - name: ARGOCD_SERVER_LOG_LEVEL
              valueFrom:
                configMapKeyRef:
                  key: server.log.level
                  name:  argocd-cmd-params-cm
                  optional: true
            - name: ARGOCD_SERVER_REPO_SERVER
              valueFrom:
                configMapKeyRef:
                  key: repo.server
                  name:  argocd-cmd-params-cm
                  optional: true
            - name: ARGOCD_SERVER_DEX_SERVER
              valueFrom:
                configMapKeyRef:
                  key: server.dex.server
                  name:  argocd-cmd-params-cm
                  optional: true
            - name: ARGOCD_SERVER_DISABLE_AUTH
              valueFrom:
                configMapKeyRef:
                  key: server.disable.auth
                  name:  argocd-cmd-params-cm
                  optional: true
            - name: ARGOCD_SERVER_ENABLE_GZIP
              valueFrom:
                configMapKeyRef:
                  key: server.enable.gzip
                  name:  argocd-cmd-params-cm
                  optional: true
            - name: ARGOCD_SERVER_REPO_SERVER_TIMEOUT_SECONDS
              valueFrom:
                configMapKeyRef:
                  key: server.repo.server.timeout.seconds
                  name:  argocd-cmd-params-cm
                  optional: true
            - name: ARGOCD_SERVER_X_FRAME_OPTIONS
              valueFrom:
                configMapKeyRef:
                  key: server.x.frame.options
                  name:  argocd-cmd-params-cm
                  optional: true
            - name: ARGOCD_SERVER_CONTENT_SECURITY_POLICY
              valueFrom:
                configMapKeyRef:
                  key: server.content.security.policy
                  name:  argocd-cmd-params-cm
                  optional: true
            - name: ARGOCD_SERVER_REPO_SERVER_PLAINTEXT
              valueFrom:
                configMapKeyRef:
                  key: server.repo.server.plaintext
                  name:  argocd-cmd-params-cm
                  optional: true
            - name: ARGOCD_SERVER_REPO_SERVER_STRICT_TLS
              valueFrom:
                configMapKeyRef:
                  key: server.repo.server.strict.tls
                  name:  argocd-cmd-params-cm
                  optional: true
            - name: ARGOCD_SERVER_DEX_SERVER_PLAINTEXT
              valueFrom:
                configMapKeyRef:
                  key: server.dex.server.plaintext
                  name:  argocd-cmd-params-cm
                  optional: true
            - name: ARGOCD_SERVER_DEX_SERVER_STRICT_TLS
              valueFrom:
                configMapKeyRef:
                  key: server.dex.server.strict.tls
                  name:  argocd-cmd-params-cm
                  optional: true
            - name: ARGOCD_TLS_MIN_VERSION
              valueFrom:
                configMapKeyRef:
                  key: server.tls.minversion
                  name:  argocd-cmd-params-cm
                  optional: true
            - name: ARGOCD_TLS_MAX_VERSION
              valueFrom:
                configMapKeyRef:
                  key: server.tls.maxversion
                  name:  argocd-cmd-params-cm
                  optional: true
            - name: ARGOCD_TLS_CIPHERS
              valueFrom:
                configMapKeyRef:
                  key: server.tls.ciphers
                  name:  argocd-cmd-params-cm
                  optional: true
            - name: ARGOCD_SERVER_CONNECTION_STATUS_CACHE_EXPIRATION
              valueFrom:
                configMapKeyRef:
                  key: server.connection.status.cache.expiration
                  name:  argocd-cmd-params-cm
                  optional: true
            - name: ARGOCD_SERVER_OIDC_CACHE_EXPIRATION
              valueFrom:
                configMapKeyRef:
                  key: server.oidc.cache.expiration
                  name:  argocd-cmd-params-cm
                  optional: true
            - name: ARGOCD_SERVER_LOGIN_ATTEMPTS_EXPIRATION
              valueFrom:
                configMapKeyRef:
                  key: server.login.attempts.expiration
                  name:  argocd-cmd-params-cm
                  optional: true
            - name: ARGOCD_SERVER_STATIC_ASSETS
              valueFrom:
                configMapKeyRef:
                  key: server.staticassets
                  name:  argocd-cmd-params-cm
                  optional: true
            - name: ARGOCD_APP_STATE_CACHE_EXPIRATION
              valueFrom:
                configMapKeyRef:
                  key: server.app.state.cache.expiration
                  name:  argocd-cmd-params-cm
                  optional: true
            - name: REDIS_SERVER
              valueFrom:
                configMapKeyRef:
                  key: redis.server
                  name:  argocd-cmd-params-cm
                  optional: true
            - name: REDIS_COMPRESSION
              valueFrom:
                configMapKeyRef:
                  key: redis.compression
                  name:  argocd-cmd-params-cm
                  optional: true
            - name: REDISDB
              valueFrom:
                configMapKeyRef:
                  key: redis.db
                  name:  argocd-cmd-params-cm
                  optional: true
            - name: ARGOCD_DEFAULT_CACHE_EXPIRATION
              valueFrom:
                configMapKeyRef:
                  key: server.default.cache.expiration
                  name:  argocd-cmd-params-cm
                  optional: true
            - name: ARGOCD_MAX_COOKIE_NUMBER
              valueFrom:
                configMapKeyRef:
                  key: server.http.cookie.maxnumber
                  name:  argocd-cmd-params-cm
                  optional: true
            - name: ARGOCD_SERVER_LISTEN_ADDRESS
              valueFrom:
                configMapKeyRef:
                  key: server.listen.address
                  name:  argocd-cmd-params-cm
                  optional: true
            - name: ARGOCD_SERVER_METRICS_LISTEN_ADDRESS
              valueFrom:
                configMapKeyRef:
                  key: server.metrics.listen.address
                  name:  argocd-cmd-params-cm
                  optional: true
            - name: ARGOCD_SERVER_OTLP_ADDRESS
              valueFrom:
                configMapKeyRef:
                  key: otlp.address
                  name:  argocd-cmd-params-cm
                  optional: true
            - name: ARGOCD_SERVER_OTLP_INSECURE
              valueFrom:
                configMapKeyRef:
                  key: otlp.insecure
                  name:  argocd-cmd-params-cm
                  optional: true
            - name: ARGOCD_SERVER_OTLP_HEADERS
              valueFrom:
                configMapKeyRef:
                  key: otlp.headers
                  name:  argocd-cmd-params-cm
                  optional: true
            - name: ARGOCD_APPLICATION_NAMESPACES
              valueFrom:
                configMapKeyRef:
                  key: application.namespaces
                  name:  argocd-cmd-params-cm
                  optional: true
            - name: ARGOCD_SERVER_ENABLE_PROXY_EXTENSION
              valueFrom:
                configMapKeyRef:
                  key: server.enable.proxy.extension
                  name:  argocd-cmd-params-cm
                  optional: true
            - name: ARGOCD_K8SCLIENT_RETRY_MAX
              valueFrom:
                configMapKeyRef:
                  key: server.k8sclient.retry.max
                  name:  argocd-cmd-params-cm
                  optional: true
            - name: ARGOCD_K8SCLIENT_RETRY_BASE_BACKOFF
              valueFrom:
                configMapKeyRef:
                  key: server.k8sclient.retry.base.backoff
                  name:  argocd-cmd-params-cm
                  optional: true
            - name: ARGOCD_API_CONTENT_TYPES
              valueFrom:
                configMapKeyRef:
                  key: server.api.content.types
                  name:  argocd-cmd-params-cm
                  optional: true
            - name: ARGOCD_SERVER_WEBHOOK_PARALLELISM_LIMIT
              valueFrom:
                configMapKeyRef:
                  key: server.webhook.parallelism.limit
                  name:  argocd-cmd-params-cm
                  optional: true
            - name: ARGOCD_APPLICATIONSET_CONTROLLER_ENABLE_NEW_GIT_FILE_GLOBBING
              valueFrom:
                configMapKeyRef:
                  key: applicationsetcontroller.enable.new.git.file.globbing
                  name:  argocd-cmd-params-cm
                  optional: true
            - name: ARGOCD_APPLICATIONSET_CONTROLLER_SCM_ROOT_CA_PATH
              valueFrom:
                configMapKeyRef:
                  key: applicationsetcontroller.scm.root.ca.path
                  name:  argocd-cmd-params-cm
                  optional: true
            - name: ARGOCD_APPLICATIONSET_CONTROLLER_ALLOWED_SCM_PROVIDERS
              valueFrom:
                configMapKeyRef:
                  key: applicationsetcontroller.allowed.scm.providers
                  name:  argocd-cmd-params-cm
                  optional: true
            - name: ARGOCD_APPLICATIONSET_CONTROLLER_ENABLE_SCM_PROVIDERS
              valueFrom:
                configMapKeyRef:
                  key: applicationsetcontroller.enable.scm.providers
                  name:  argocd-cmd-params-cm
                  optional: true
            - name: ARGOCD_HYDRATOR_ENABLED
              valueFrom:
                configMapKeyRef:
                  key: hydrator.enabled
                  name:  argocd-cmd-params-cm
                  optional: true
          {{- if .Values.pod.containers.server.healthz }}
          startupProbe:
            httpGet:
              path: /healthz?full=true
              port: http
            timeoutSeconds: 1
            periodSeconds: 5
            successThreshold: 1
            failureThreshold: 30
          livenessProbe:
            httpGet:
              path: /healthz?full=true
              port: http
            timeoutSeconds: 1
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 10
          readinessProbe:
            httpGet:
              path: /healthz
              port: http
            timeoutSeconds: 1
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
          {{- end }}