---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "redis.fullname" . }}-script
  labels:
    app.kubernetes.io/component: redis
    {{- include "redis.labels" . | nindent 4 }}
    {{- include "common.labels" ( dict "labels" (list .Values.global.labels .Values.labels) ) | nindent 4 }}
  annotations:
    {{- include "common.annotations" ( dict "annotations" (list .Values.global.annotations .Values.annotations) ) | nindent 4 }}
data:
  healthz.sh: {{- .Files.Get "scripts/healthz.sh" | toYaml | indent 2 }}