---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "reposerver.fullname" . }}
  labels:
    app.kubernetes.io/component: repo-server
    {{- include "reposerver.labels" . | nindent 4 }}
    {{- include "common.labels" ( dict "labels" (list .Values.global.labels .Values.labels) ) | nindent 4 }}
  annotations:
    {{- include "common.annotations" ( dict "annotations" (list .Values.global.annotations .Values.annotations) ) | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  {{- if and .Values.service.clusterIP (eq .Values.service.type "ClusterIP") }}
  clusterIP: {{ .Values.service.clusterIP }}
  {{- end }}
  {{- if .Values.service.ipFamilyPolicy }}
  ipFamilyPolicy: {{ .Values.service.ipFamilyPolicy }}
  {{- end }}
  {{- with .Values.service.ipFamilies }}
  ipFamilies:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  ports:
    - name: http
      protocol: TCP
      targetPort: {{ .Values.service.ports.http.port }}
      port: {{ .Values.service.ports.http.port }}
      {{- if and .Values.service.ports.http.nodePort (eq .Values.service.ports.http.type "NodePort") }}
      nodePort: {{ .Values.service.ports.http.nodePort }}
      {{- end }}
    - name: metrics
      protocol: TCP
      targetPort: {{ .Values.service.ports.metrics.port }}
      port: {{ .Values.service.ports.metrics.port }}
      {{- if and .Values.service.ports.metrics.nodePort (eq .Values.service.ports.metrics.type "NodePort") }}
      nodePort: {{ .Values.service.ports.metrics.nodePort }}
      {{- end }}
  {{- if .Values.service.publishNotReadyAddresses }}
  publishNotReadyAddresses: true
  {{- end }}
  selector:
    {{- include "reposerver.selectorLabels" . | nindent 4 }}
    argocd.deployment/type: repo-server
