---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "vaultwarden.fullname" . }}
  labels:
    {{- include "vaultwarden.labels" . | nindent 4 }}
    {{- include "common.labels" ( dict "labels" (list .Values.global.labels .Values.labels) ) | nindent 4 }}
  annotations:
    {{- include "common.annotations" ( dict "annotations" (list .Values.global.annotations .Values.annotations) ) | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  revisionHistoryLimit: {{ .Values.revisionHistoryLimit }}
  minReadySeconds: {{ .Values.minReadySeconds }}
  {{- with .Values.strategy }}
  strategy:
    {{- . | toYaml | nindent 8 }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "vaultwarden.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        {{- include "common.annotations" ( dict "annotations" (list .Values.global.annotations .Values.annotations .Values.pod.annotations) ) | nindent 8 }}
      labels:
        {{- include "common.labels" ( dict "labels" (list .Values.global.labels .Values.labels .Values.pod.labels) ) | nindent 8 }}
        {{- include "vaultwarden.selectorLabels" . | nindent 8 }}
    spec:
      serviceAccountName: sa-{{ include "vaultwarden.fullname" . }}
      {{- include "common.images.pullSecrets" ( dict "images" (list .Values.image) "global" .Values.global) | nindent 6 }}
      {{- with .Values.pod.affinity }}
      affinity:
        {{- . | toYaml | nindent 8 }}
      {{- end }}
      {{- with .Values.pod.securityContext }}
      securityContext:
        {{- . | toYaml | nindent 8 }}
      {{- end }}
      {{- with .Values.pod.nodeSelector }}
      nodeSelector:
        {{- . | toYaml | nindent 8 }}
      {{- end }}
      {{- with .Values.pod.tolerations }}
      tolerations:
        {{- . | toYaml | nindent 8 }}
      {{- end }}
      {{- with .Values.pod.schedulerName }}
      schedulerName: {{ . | quote }}
      {{- end }}
      {{- with .Values.pod.priorityClassName }}
      priorityClassName: {{ . | quote }}
      {{- end }}   
      {{- with .Values.pod.terminationGracePeriodSeconds }}
      terminationGracePeriodSeconds: {{ . }}
      {{- end }}
      {{- with .Values.pod.initContainers }}
      initContainers:
        {{- . | toYaml | nindent 8 }}
      {{- end }}
      volumes:
        {{- with (concat .Values.pod.extraVolumes .Values.global.extraVolumes) }}
        {{- . | toYaml | nindent 8 }}
        {{- end }}
        - name: data
          {{- if .Values.persistence.enabled }}
          persistenceVolumeClaim:
            claimName: {{ include "vaultwarden.fullname" . }}-data
          {{- else }}
          emptyDir: {}
          {{- end }}
      containers:
        {{- with .Values.pod.sidecarContainers }}
        {{- . | toYaml | nindent 8 }}
        {{- end }}
        - name: vaultwarden
          image: {{ include "common.images.image" ( dict "imageRoot" .Values.image "global" .Values.global "chart" .Chart ) }}
          imagePullPolicy: {{ include "common.images.pullPolicy" ( dict "imageRoot" .Values.image "global" .Values.global ) }}
          {{- with .Values.pod.containers.vaultwarden.command }}
          command: 
            {{- . | toYaml | nindent 12 }}
          {{- end }}
          {{- with .Values.pod.containers.vaultwarden.args }}
          args: 
            {{- . | toYaml | nindent 12 }}
          {{- end }}
          {{- with .Values.pod.containers.vaultwarden.securityContext }}
          securityContext: 
            {{- . | toYaml | nindent 12 }}
          {{- end }}
          {{- with .Values.pod.containers.vaultwarden.workingDir }}
          workingDir: {{ . | quote }}
          {{- end }}
          {{- with .Values.pod.containers.vaultwarden.resources }}
          resources:
            {{- . | toYaml | nindent 12 }}
          {{- end }}
          ports:
            - name: http
              containerPort: {{ .Values.service.ports.http.port }}
              protocol: TCP
              {{- with .Values.service.ports.http.hostPort }}
              hostPort: {{ . }}
              {{- end }}
            - name: websocket
              containerPort: {{ .Values.service.ports.websocket.port }}
              protocol: TCP
              {{- with .Values.service.ports.websocket.hostPort }}
              hostPort: {{ . }}
              {{- end }}
          volumeMounts:
            {{- with (concat .Values.pod.containers.vaultwarden.extraVolumeMounts 
                             .Values.pod.extraVolumeMounts 
                             .Values.global.extraVolumeMounts) }}
            {{- . | toYaml | nindent 12 }}
            {{- end }}
            - name: data
              mountPath: /data
          {{- with (concat .Values.pod.containers.vaultwarden.extraEnvFrom .Values.pod.extraEnvFrom) }}
          envFrom:
            {{- . | toYaml | nindent 12 }}
          {{- end }}
          {{- with (concat .Values.pod.containers.vaultwarden.extraEnvs .Values.pod.extraEnvs) }}
          env:
            {{- . | toYaml | nindent 12 }}
          {{- end }}
          {{- if .Values.pod.containers.vaultwarden.healthz }}
          startupProbe:
            httpGet:
              path: /
              port: http
            timeoutSeconds: 1
            periodSeconds: 5
            successThreshold: 1
            failureThreshold: 30
          livenessProbe:
            httpGet:
              path: /
              port: http
            timeoutSeconds: 1
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 10
          readinessProbe:
            httpGet:
              path: /
              port: http
            timeoutSeconds: 1
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
          {{- end }}